In [22]:
import pandas as pd
import numpy as np

In [27]:
dp = pd.read_csv('experimentsin.csv')

In [28]:
dp

,Unnamed: 0,x0,z0,x3,y3,z3,x4,y4,z4
0,0,6.000000,30.192158,6.000000,51,30.192158,4.000000,62,29.391528
1,1,4.472136,33.216374,4.472136,52,33.216374,2.828427,62,29.348702
2,2,4.472136,28.451263,4.472136,51,27.107868,3.464102,63,30.297837
3,3,5.656854,29.132863,5.656854,51,29.132863,4.898979,62,28.482221
4,4,2.828427,31.563104,3.464102,52,32.136997,2.000000,62,29.161980
...,...,...,...,...,...,...,...,...,...
95,95,5.291503,30.790149,5.291503,52,30.790149,6.324555,62,31.439942
96,96,4.898979,28.357886,4.898979,52,28.357886,4.472136,63,32.270545
97,97,4.472136,31.465964,4.472136,51,31.465964,4.000000,62,27.292561
98,98,4.472136,28.655245,4.472136,52,28.655245,4.000000,61,28.677873
99,99,4.000000,31.635048,4.000000,52,31.635048,4.000000,63,29.467974

In [53]:
(dp['x4']==0).sum()

4