In [1]:
import pandas as pd
import numpy as np

In [28]:
dp = pd.read_csv('experiments3.csv')

In [29]:
dp

,Unnamed: 0,x0,x1,y1,x2,y2,x3,y3,x4,y4
0,0,41.084882,41.084882,1,41.084882,1,41.084882,81,41.084882,110
1,1,50.134469,50.134469,1,50.134469,1,50.134469,80,50.134469,108
2,2,58.393316,58.393316,80,58.393316,5,58.780288,83,58.393316,111
3,3,66.197897,66.197897,1,66.197897,1,66.197897,81,66.197897,111
4,4,71.853591,71.853591,174,71.853591,2,73.232155,83,71.853591,109
5,5,81.454779,81.454779,348,81.454779,9,81.657410,82,81.454779,111
6,6,87.862184,87.862184,656,87.862184,15,89.702916,85,87.958108,110
7,7,97.376211,97.376211,143,97.376211,1980,99.291245,84,98.143019,112
8,8,102.742164,102.742164,1307,102.742164,239,106.493365,84,102.742164,109
9,9,111.376416,111.376416,8634,111.376416,7729,112.845092,84,112.063001,110
10,10,115.913598,115.913598,35482,115.913598,2199,120.296493,87,115.913598,108
11,11,124.353468,124.353468,55707,124.353468,38427,129.271678,83,124.353468,110
12,12,131.869267,131.869267,60461,131.869267,20378,140.464218,86,131.869267,107
13,13,140.557245,140.798800,500000,140.557245,139967,146.518476,84,140.557245,110
14,14,148.910577,148.910577,133789,148.910577,55276,153.133413,83,149.278909,110
15,15,152.939448,153.235850,500000,152.939448,143034,163.416427,91,153.235850,110
16,16,162.395115,162.963390,500000,162.395115,348212,173.803300,87,162.679258,111
17,17,168.351053,169.564654,500000,168.351053,80216,176.344036,85,170.853182,110
18,18,176.290510,176.290510,229682,177.516233,500000,187.202472,92,178.141723,112
19,19,185.143327,187.413859,500000,186.717369,500000,193.362041,84,188.733785,110

In [26]:
equal_values_count = (dp['y1']>=dp['y2']).sum()

In [27]:
equal_values_count

109